name: React Compt based Website
on: [push]
jobs:
  build:
    
    runs-on: ubuntu-latest
    name: Deploying to surge
      
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v2.1.0
        with:
          # Yarn command
            cmd: install  # npm install / yarn install
      - name: Creating build
        run: yarn build
      - name: Installation surge
        run: npm install -g surge      
      - name: Run surge / deploying on surge
        run: surge ./build hn-reactapp-compt-session3.surge.sh --token ${{secrets.SURGE_TOKEN}}  
